//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XctLogin.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;


    public partial class User
    {

        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter a username.")]
        [Display(Name = "Username")]
        [Remote("doesUsernameExist", "Users", HttpMethod = "POST", ErrorMessage = "Username does not exist!")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Please enter a password.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [System.ComponentModel.DataAnnotations.Compare("Password")]
        public string Name { get; set; }
    }
}
